config/routes.rb
Contests::Application.routes.draw do
  resources :entries

  resources :contests do |entries|
    resources :entries
  end
  resources :contests, :path => "win-a-million-rupees"# :as => "win-a-million-rupees" 

end

app/models/contest.rb
class Contest < ActiveRecord::Base
end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :set_contest, only: [:show, :edit, :update, :destroy]

  # GET /contests
  # GET /contests.json
  def index
    @contests = Contest.all
  end

  # GET /contests/1
  # GET /contests/1.json
  def show
  end

  # GET /contests/new
  def new
    @contest = Contest.new
  end

  # GET /contests/1/edit
  def edit
  end

  # POST /contests
  # POST /contests.json
  def create
    @contest = Contest.new(contest_params)

    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contest }
      else
        format.html { render action: 'new' }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contests/1
  # PATCH/PUT /contests/1.json
  def update
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contest
      @contest = Contest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contest_params
      params.require(:contest).permit(:title, :uid, :teaser, :image, :content, :apply_start, :apply_end, :vote_begin, :vote_begin_display, :vote_end, :vote_end_display, :theme, :mall_ids, :permission, :entry_method, :entry_frequency, :winner_qualification, :prize, :winner_notification, :redemption_method, :announcement_date, :confirmation_email_subject, :alert_email_subject, :alert_email_address, :confirmation_email_body, :alert_email_body, :url, :already_entered_text, :not_begun_text, :over_text, :additional_information, :design_and_copy, :success_text, :rules_url, :report_type, :report_params, :announcement_method)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :set_contest, only: [:index]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end
    def set_contest
      @contest = Contest.find(params[:contest_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:contest_id, :title, :user_id, :teaser, :image, :content, :date_initiate, :date_expire, :first_name, :last_name, :email, :phone, :street_address, :city, :state, :zipcode, :video, :mallid, :vote_total_display, :approved, :over_13)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/contests/_form.html.erb
<%= form_for(@contest) do |f| %>
  <% if @contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% @contest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :teaser %><br>
    <%= f.text_area :teaser %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :apply_start %><br>
    <%= f.datetime_select :apply_start %>
  </div>
  <div class="field">
    <%= f.label :apply_end %><br>
    <%= f.datetime_select :apply_end %>
  </div>
  <div class="field">
    <%= f.label :vote_begin %><br>
    <%= f.datetime_select :vote_begin %>
  </div>
  <div class="field">
    <%= f.label :vote_begin_display %><br>
    <%= f.text_field :vote_begin_display %>
  </div>
  <div class="field">
    <%= f.label :vote_end %><br>
    <%= f.datetime_select :vote_end %>
  </div>
  <div class="field">
    <%= f.label :vote_end_display %><br>
    <%= f.text_field :vote_end_display %>
  </div>
  <div class="field">
    <%= f.label :theme %><br>
    <%= f.text_area :theme %>
  </div>
  <div class="field">
    <%= f.label :mall_ids %><br>
    <%= f.text_area :mall_ids %>
  </div>
  <div class="field">
    <%= f.label :permission %><br>
    <%= f.text_field :permission %>
  </div>
  <div class="field">
    <%= f.label :entry_method %><br>
    <%= f.text_field :entry_method %>
  </div>
  <div class="field">
    <%= f.label :entry_frequency %><br>
    <%= f.text_field :entry_frequency %>
  </div>
  <div class="field">
    <%= f.label :winner_qualification %><br>
    <%= f.text_field :winner_qualification %>
  </div>
  <div class="field">
    <%= f.label :prize %><br>
    <%= f.text_field :prize %>
  </div>
  <div class="field">
    <%= f.label :winner_notification %><br>
    <%= f.text_field :winner_notification %>
  </div>
  <div class="field">
    <%= f.label :redemption_method %><br>
    <%= f.text_field :redemption_method %>
  </div>
  <div class="field">
    <%= f.label :announcement_date %><br>
    <%= f.datetime_select :announcement_date %>
  </div>
  <div class="field">
    <%= f.label :confirmation_email_subject %><br>
    <%= f.text_field :confirmation_email_subject %>
  </div>
  <div class="field">
    <%= f.label :alert_email_subject %><br>
    <%= f.text_field :alert_email_subject %>
  </div>
  <div class="field">
    <%= f.label :alert_email_address %><br>
    <%= f.text_field :alert_email_address %>
  </div>
  <div class="field">
    <%= f.label :confirmation_email_body %><br>
    <%= f.text_area :confirmation_email_body %>
  </div>
  <div class="field">
    <%= f.label :alert_email_body %><br>
    <%= f.text_area :alert_email_body %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :already_entered_text %><br>
    <%= f.text_area :already_entered_text %>
  </div>
  <div class="field">
    <%= f.label :not_begun_text %><br>
    <%= f.text_area :not_begun_text %>
  </div>
  <div class="field">
    <%= f.label :over_text %><br>
    <%= f.text_field :over_text %>
  </div>
  <div class="field">
    <%= f.label :additional_information %><br>
    <%= f.text_area :additional_information %>
  </div>
  <div class="field">
    <%= f.label :design_and_copy %><br>
    <%= f.text_area :design_and_copy %>
  </div>
  <div class="field">
    <%= f.label :success_text %><br>
    <%= f.text_area :success_text %>
  </div>
  <div class="field">
    <%= f.label :rules_url %><br>
    <%= f.text_field :rules_url %>
  </div>
  <div class="field">
    <%= f.label :report_type %><br>
    <%= f.text_field :report_type %>
  </div>
  <div class="field">
    <%= f.label :report_params %><br>
    <%= f.text_area :report_params %>
  </div>
  <div class="field">
    <%= f.label :announcement_method %><br>
    <%= f.text_field :announcement_method %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contests/edit.html.erb
<h1>Editing contest</h1>

<%= render 'form' %>

<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>

app/views/contests/index.html.erb
<h1>Listing contests</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Uid</th>
      <th>Teaser</th>
      <th>Image</th>
      <th>Content</th>
      <th>Apply start</th>
      <th>Apply end</th>
      <th>Vote begin</th>
      <th>Vote begin display</th>
      <th>Vote end</th>
      <th>Vote end display</th>
      <th>Theme</th>
      <th>Mall ids</th>
      <th>Permission</th>
      <th>Entry method</th>
      <th>Entry frequency</th>
      <th>Winner qualification</th>
      <th>Prize</th>
      <th>Winner notification</th>
      <th>Redemption method</th>
      <th>Announcement date</th>
      <th>Confirmation email subject</th>
      <th>Alert email subject</th>
      <th>Alert email address</th>
      <th>Confirmation email body</th>
      <th>Alert email body</th>
      <th>Url</th>
      <th>Already entered text</th>
      <th>Not begun text</th>
      <th>Over text</th>
      <th>Additional information</th>
      <th>Design and copy</th>
      <th>Success text</th>
      <th>Rules url</th>
      <th>Report type</th>
      <th>Report params</th>
      <th>Announcement method</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contests.each do |contest| %>
      <tr>
        <td><%= contest.title %></td>
        <td><%= contest.uid %></td>
        <td><%= contest.teaser %></td>
        <td><%= contest.image %></td>
        <td><%= contest.content %></td>
        <td><%= contest.apply_start %></td>
        <td><%= contest.apply_end %></td>
        <td><%= contest.vote_begin %></td>
        <td><%= contest.vote_begin_display %></td>
        <td><%= contest.vote_end %></td>
        <td><%= contest.vote_end_display %></td>
        <td><%= contest.theme %></td>
        <td><%= contest.mall_ids %></td>
        <td><%= contest.permission %></td>
        <td><%= contest.entry_method %></td>
        <td><%= contest.entry_frequency %></td>
        <td><%= contest.winner_qualification %></td>
        <td><%= contest.prize %></td>
        <td><%= contest.winner_notification %></td>
        <td><%= contest.redemption_method %></td>
        <td><%= contest.announcement_date %></td>
        <td><%= contest.confirmation_email_subject %></td>
        <td><%= contest.alert_email_subject %></td>
        <td><%= contest.alert_email_address %></td>
        <td><%= contest.confirmation_email_body %></td>
        <td><%= contest.alert_email_body %></td>
        <td><%= contest.url %></td>
        <td><%= contest.already_entered_text %></td>
        <td><%= contest.not_begun_text %></td>
        <td><%= contest.over_text %></td>
        <td><%= contest.additional_information %></td>
        <td><%= contest.design_and_copy %></td>
        <td><%= contest.success_text %></td>
        <td><%= contest.rules_url %></td>
        <td><%= contest.report_type %></td>
        <td><%= contest.report_params %></td>
        <td><%= contest.announcement_method %></td>
        <td><%= link_to 'Show', contest %></td>
        <td><%= link_to 'Edit', edit_contest_path(contest) %></td>
        <td><%= link_to 'Destroy', contest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contest', new_contest_path %>

app/views/contests/new.html.erb
<h1>New contest</h1>

<%= render 'form' %>

<%= link_to 'Back', contests_path %>

app/views/contests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @contest.title %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @contest.uid %>
</p>

<p>
  <strong>Teaser:</strong>
  <%= @contest.teaser %>
</p>

<p>
  <strong>Image:</strong>
  <%= @contest.image %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contest.content %>
</p>

<p>
  <strong>Apply start:</strong>
  <%= @contest.apply_start %>
</p>

<p>
  <strong>Apply end:</strong>
  <%= @contest.apply_end %>
</p>

<p>
  <strong>Vote begin:</strong>
  <%= @contest.vote_begin %>
</p>

<p>
  <strong>Vote begin display:</strong>
  <%= @contest.vote_begin_display %>
</p>

<p>
  <strong>Vote end:</strong>
  <%= @contest.vote_end %>
</p>

<p>
  <strong>Vote end display:</strong>
  <%= @contest.vote_end_display %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @contest.theme %>
</p>

<p>
  <strong>Mall ids:</strong>
  <%= @contest.mall_ids %>
</p>

<p>
  <strong>Permission:</strong>
  <%= @contest.permission %>
</p>

<p>
  <strong>Entry method:</strong>
  <%= @contest.entry_method %>
</p>

<p>
  <strong>Entry frequency:</strong>
  <%= @contest.entry_frequency %>
</p>

<p>
  <strong>Winner qualification:</strong>
  <%= @contest.winner_qualification %>
</p>

<p>
  <strong>Prize:</strong>
  <%= @contest.prize %>
</p>

<p>
  <strong>Winner notification:</strong>
  <%= @contest.winner_notification %>
</p>

<p>
  <strong>Redemption method:</strong>
  <%= @contest.redemption_method %>
</p>

<p>
  <strong>Announcement date:</strong>
  <%= @contest.announcement_date %>
</p>

<p>
  <strong>Confirmation email subject:</strong>
  <%= @contest.confirmation_email_subject %>
</p>

<p>
  <strong>Alert email subject:</strong>
  <%= @contest.alert_email_subject %>
</p>

<p>
  <strong>Alert email address:</strong>
  <%= @contest.alert_email_address %>
</p>

<p>
  <strong>Confirmation email body:</strong>
  <%= @contest.confirmation_email_body %>
</p>

<p>
  <strong>Alert email body:</strong>
  <%= @contest.alert_email_body %>
</p>

<p>
  <strong>Url:</strong>
  <%= @contest.url %>
</p>

<p>
  <strong>Already entered text:</strong>
  <%= @contest.already_entered_text %>
</p>

<p>
  <strong>Not begun text:</strong>
  <%= @contest.not_begun_text %>
</p>

<p>
  <strong>Over text:</strong>
  <%= @contest.over_text %>
</p>

<p>
  <strong>Additional information:</strong>
  <%= @contest.additional_information %>
</p>

<p>
  <strong>Design and copy:</strong>
  <%= @contest.design_and_copy %>
</p>

<p>
  <strong>Success text:</strong>
  <%= @contest.success_text %>
</p>

<p>
  <strong>Rules url:</strong>
  <%= @contest.rules_url %>
</p>

<p>
  <strong>Report type:</strong>
  <%= @contest.report_type %>
</p>

<p>
  <strong>Report params:</strong>
  <%= @contest.report_params %>
</p>

<p>
  <strong>Announcement method:</strong>
  <%= @contest.announcement_method %>
</p>


<%= link_to 'Edit', edit_contest_path(@contest) %> |
<%= link_to 'Back', contests_path %>

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contest_id %><br>
    <%= f.text_field :contest_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :teaser %><br>
    <%= f.text_area :teaser %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :date_initiate %><br>
    <%= f.datetime_select :date_initiate %>
  </div>
  <div class="field">
    <%= f.label :date_expire %><br>
    <%= f.datetime_select :date_expire %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br>
    <%= f.text_field :street_address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :video %><br>
    <%= f.text_field :video %>
  </div>
  <div class="field">
    <%= f.label :mallid %><br>
    <%= f.text_field :mallid %>
  </div>
  <div class="field">
    <%= f.label :vote_total_display %><br>
    <%= f.text_field :vote_total_display %>
  </div>
  <div class="field">
    <%= f.label :approved %><br>
    <%= f.text_field :approved %>
  </div>
  <div class="field">
    <%= f.label :over_13 %><br>
    <%= f.text_field :over_13 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
Contest: 
<p>
  <strong>Title:</strong>
  <%= @contest.title %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @contest.uid %>
</p>

<p>
  <strong>Teaser:</strong>
  <%= @contest.teaser %>
</p>

<h1>Listing entries</h1>

<table>
  <thead>
    <tr>
      <th>Contest</th>
      <th>Title</th>
      <th>User</th>
      <th>Teaser</th>
      <th>Image</th>
      <th>Content</th>
      <th>Date initiate</th>
      <th>Date expire</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Street address</th>
      <th>City</th>
      <th>State</th>
      <th>Zipcode</th>
      <th>Video</th>
      <th>Mallid</th>
      <th>Vote total display</th>
      <th>Approved</th>
      <th>Over 13</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.contest_id %></td>
        <td><%= entry.title %></td>
        <td><%= entry.user_id %></td>
        <td><%= entry.teaser %></td>
        <td><%= entry.image %></td>
        <td><%= entry.content %></td>
        <td><%= entry.date_initiate %></td>
        <td><%= entry.date_expire %></td>
        <td><%= entry.first_name %></td>
        <td><%= entry.last_name %></td>
        <td><%= entry.email %></td>
        <td><%= entry.phone %></td>
        <td><%= entry.street_address %></td>
        <td><%= entry.city %></td>
        <td><%= entry.state %></td>
        <td><%= entry.zipcode %></td>
        <td><%= entry.video %></td>
        <td><%= entry.mallid %></td>
        <td><%= entry.vote_total_display %></td>
        <td><%= entry.approved %></td>
        <td><%= entry.over_13 %></td>
        <td><%= link_to 'Show', [@contest, entry] %></td>
        <td><%= link_to 'Edit',  [:edit, @contest, @entry] %></td>
        <td><%= link_to 'Destroy', [@contest, @entry], method: :delete, data: { confirm: "Are you sure you want to delete this entry?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_contest_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contest:</strong>
  <%= @entry.contest_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @entry.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @entry.user_id %>
</p>

<p>
  <strong>Teaser:</strong>
  <%= @entry.teaser %>
</p>

<p>
  <strong>Image:</strong>
  <%= @entry.image %>
</p>

<p>
  <strong>Content:</strong>
  <%= @entry.content %>
</p>

<p>
  <strong>Date initiate:</strong>
  <%= @entry.date_initiate %>
</p>

<p>
  <strong>Date expire:</strong>
  <%= @entry.date_expire %>
</p>

<p>
  <strong>First name:</strong>
  <%= @entry.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @entry.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @entry.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @entry.phone %>
</p>

<p>
  <strong>Street address:</strong>
  <%= @entry.street_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @entry.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @entry.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @entry.zipcode %>
</p>

<p>
  <strong>Video:</strong>
  <%= @entry.video %>
</p>

<p>
  <strong>Mallid:</strong>
  <%= @entry.mallid %>
</p>

<p>
  <strong>Vote total display:</strong>
  <%= @entry.vote_total_display %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @entry.approved %>
</p>

<p>
  <strong>Over 13:</strong>
  <%= @entry.over_13 %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contests</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>